const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const topics={
"medische-term":["Wat betekent deze medische uitdrukking?","We splitsen een medische term in drie lagen: wat is feitelijk gemeten of beschreven, wat leidt de arts daaruit af, en wat bewijst de term níét automatisch. Zo blijven bevinding, interpretatie en diagnose uit elkaar.","Voorbeeld: een EMG-afwijking is een bevinding; de diagnose die eraan wordt gekoppeld is een volgende stap.",[]],
voeding:["Kan voeding een rol spelen?","Voeding kan gezondheid beïnvloeden via energie, bouwstoffen, tekorten, darmmicrobioom en stofwisseling. Of voeding bij een specifieke neurologische aandoening oorzaak of behandeling is, moet per persoon en per aandoening worden onderzocht.","Begin met meetbare vragen: wat eet MV, zijn tekorten aangetoond en veranderde er iets in de tijd?",[["NIH — Healthy eating","https://www.nia.nih.gov/health/healthy-eating-nutrition-and-diet"]]],
japan:["Wat was het verhaal uit Japan?","Op het Kii-schiereiland in Japan zijn historische clusters beschreven van ALS, parkinsonisme en dementie. Vergelijkbare clusters zijn beschreven op Guam en in West-Nieuw-Guinea. Onderzoekers kijken naar een combinatie van erfelijke kwetsbaarheid en omgevingsfactoren; één definitieve oorzaak is niet bewezen.","Het voorbeeld laat vooral zien waarom je tijd, omgeving, blootstelling en biologische mechanismen naast elkaar moet leggen.",[["PubMed — Western Pacific ALS/PDC","https://pubmed.ncbi.nlm.nih.gov/34635325/"],["PubMed — Kii review 2026","https://pubmed.ncbi.nlm.nih.gov/42745716/"]]],
autoimmuun:["Wat is een auto-immuunziekte?","Je afweersysteem hoort indringers te herkennen. Bij auto-immuniteit raakt die herkenning ontregeld en richt de afweer zich ook tegen onderdelen van het eigen lichaam.","‘Auto-immuun’ beschrijft een mechanisme; het zegt nog niet automatisch welke ziekte iemand heeft of waardoor het begon.",[["MedlinePlus — Autoimmune diseases","https://medlineplus.gov/autoimmunediseases.html"]]],
holistisch:["Wat is een holistische kijk op geneeskunde?","Holistisch kijken betekent dat je een mens niet alleen als één orgaan of diagnose bekijkt. Je brengt lichaam, voeding, slaap, beweging, stress, psyche, sociale omgeving, zingeving, blootstellingen en behandeling samen.","Breed kijken betekent niet dat alle verklaringen even sterk zijn. We houden bewijs, hypothese en ervaring uit elkaar.",[["NCCIH — Whole Person Health","https://www.nccih.nih.gov/health/whole-person-health-what-you-need-to-know"]]],
behandeling:["Waarom krijgt MV deze behandeling?","Splits de vraag op: wat is de diagnose of werkdiagnose, welk mechanisme probeert de behandeling te beïnvloeden, welk effect verwacht de behandelaar en waaraan wordt gemeten of het werkt?","Vraag ook wanneer men doorgaat, aanpast of stopt.",[]],
homeopathie:["Wat is homeopathie?","Homeopathie is een complementaire geneeswijze gebaseerd op ‘het gelijke met het gelijkende’ en sterk verdunde bereidingen. De benadering kijkt vaak naar het totale klachtenpatroon.","Voor een specifieke werking van sterk verdunde middelen boven placebo is in goed gecontroleerd onderzoek geen overtuigend bewijs aangetoond.",[["NCCIH — Homeopathy","https://www.nccih.nih.gov/health/homeopathy"]]],
spike:["Wat is het spike-eiwit?","Het spike-eiwit zit aan de buitenkant van SARS-CoV-2 en helpt het virus zich aan menselijke cellen te binden. Bij infectie maakt het virus spike als onderdeel van zijn vermenigvuldiging; bij mRNA-vaccins maken sommige cellen tijdelijk een aangepaste vorm zodat het afweersysteem leert herkennen.","Bij een concrete casus moet onderscheid worden gemaakt tussen infectie, vaccinatie, immuunreactie en objectieve medische bevindingen.",[["CDC — mRNA vaccines","https://www.cdc.gov/covid/vaccines/how-they-work.html"]]],
mrna:["Wat is mRNA-therapie?","mRNA is een tijdelijk boodschappenbriefje waarmee een cel een eiwit maakt. Bij een mRNA-behandeling wordt zo’n instructie toegediend, meestal verpakt in vetdeeltjes. De cel leest de instructie en breekt het mRNA daarna weer af.","De veiligheidsvraag is altijd specifiek: welke instructie, welke verpakking, welke dosis, welke doelgroep en welk doel?",[["EMA — Comirnaty","https://www.ema.europa.eu/en/medicines/human/EPAR/comirnaty"]]],
rechten:["Wat mag MV zelf beslissen?","MV heeft recht op begrijpelijke informatie, overleg, toestemming geven of weigeren, inzage/kopie van het dossier en een second opinion. De arts houdt tegelijk een eigen professionele verantwoordelijkheid.","De praktische vraag is: zijn de mogelijkheden en onzekerheden zó uitgelegd dat MV zelf kan kiezen?",[["Rijksoverheid — patiëntenrechten","https://www.rijksoverheid.nl/onderwerpen/rechten-van-patient-en-privacy/rechten-bij-een-medische-behandeling"],["KNMG — Gedragscode","https://www.knmg.nl/actueel/dossiers/kwaliteit-en-veiligheid-2/gedragscode-voor-artsen"]]],
status:["Casusstatus: eerst reconstrueren","Leg naast elkaar: klachten, tijdlijn, objectieve bevindingen, diagnose of werkdiagnose, behandeling en effect. Voeg alternatieve verklaringen pas daarna toe.","Vaste vragen: wat is aangetoond, aangenomen, uitgesloten en nog niet onderzocht?",[]]
};
const map=[[/japan|kii|guam|cycad|bmaa|mam/i,"japan"],[/auto.?immuun|afweer/i,"autoimmuun"],[/m.?rna/i,"mrna"],[/spike/i,"spike"],[/homeopath/i,"homeopathie"],[/holist/i,"holistisch"],[/voeding|eten|dieet|vitamine|tekort/i,"voeding"],[/recht|second opinion|dossier|weigeren|beslis/i,"rechten"],[/behandel|medicijn|therapie/i,"behandeling"],[/term|beteken|uitslag|emg|mri/i,"medische-term"]];
function esc(s){return s.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function show(k,q=""){const t=topics[k];if(!t)return;$("#answer").innerHTML=(q?'<p class="eyebrow">VRAAG: '+esc(q)+'</p>':"")+'<h3>'+t[0]+'</h3><p>'+t[1]+'</p><div class="note">'+t[2]+'</div>'+(t[3].length?'<div class="source-row">'+t[3].map(x=>'<a target="_blank" rel="noopener" href="'+x[1]+'">'+x[0]+' ↗</a>').join("")+'</div>':"");$("#answer").classList.add("show")}
function save(q){let a=JSON.parse(localStorage.getItem("mv_questions")||"[]");if(!a.includes(q))a.unshift(q);localStorage.setItem("mv_questions",JSON.stringify(a.slice(0,30)))}
$("#askForm").addEventListener("submit",e=>{e.preventDefault();let q=$("#question").value.trim();if(!q)return;save(q);let m=map.find(x=>x[0].test(q));if(m)show(m[1],q);else{$("#answer").innerHTML='<p class="eyebrow">VRAAG BEWAARD</p><h3>'+esc(q)+'</h3><p>Deze vraag is lokaal bewaard onder <b>Vragen</b>. In een volgende versie kan vrije dialoog direct aan de kennislaag worden gekoppeld.</p>';$("#answer").classList.add("show")}});
$("#clearBtn").addEventListener("click",()=>{$("#question").value="";$("#answer").classList.remove("show")});
$$("[data-topic]").forEach(b=>b.addEventListener("click",()=>show(b.dataset.topic,b.textContent.trim())));
const cloud=["Auto-immuniteit","Voeding","Infecties","Stress & zenuwstelsel","Slaap","Beweging","Darm & microbioom","Omgeving","Toxische blootstelling","Homeopathie","Acupunctuur","Traditionele geneeskunde","mRNA","Spike-eiwit","Japan / Guam","Life Extension","Spiritualiteit & zingeving"];
const views={
timeline:["Tijdlijn",'<div class="timeline"><div class="event"><time>BEGIN</time><div><b>Eerste merkbare verandering</b><br><input placeholder="Wat veranderde er als eerste?"></div></div><div class="event"><time>DAARNA</time><div><b>Eerste arts / onderzoek</b><br><input placeholder="Wie, welk onderzoek, wat kwam eruit?"></div></div><div class="event"><time>TRIGGERS?</time><div><b>Gebeurtenissen vóór klachten</b><br><input placeholder="infectie, medicatie, vaccinatie, operatie, blootstelling, stress…"></div></div><div class="event"><time>NU</time><div><b>Behandeling en effect</b><br><input placeholder="Wat gebeurt nu en wat merkt MV daarvan?"></div></div></div><p class="empty">Deze velden worden in V0.1 nog niet opgeslagen.</p>'],
documents:["Documenten",'<div class="cards"><div class="mini-card"><b>Onderzoeken</b><p>MRI, EMG, bloed, liquor, genetiek en overige uitslagen.</p></div><div class="mini-card"><b>Brieven</b><p>Neuroloog, huisarts, behandelplan, second opinion en ontslagbrieven.</p></div><div class="mini-card"><b>Literatuur</b><p>PubMed, richtlijnen, reviews en historische bronnen.</p></div></div><p class="empty">Persoonlijke uploads horen pas in een beveiligde volgende stap.</p>'],
sources:["Bronnen",'<div class="cards"><div class="mini-card"><b>1. Gewone uitleg</b><p>Zonder jargon.</p></div><div class="mini-card"><b>2. Medische bron</b><p>Richtlijn, EMA/WHO/Rijksoverheid of PubMed.</p></div><div class="mini-card"><b>3. Oorspronkelijk onderzoek</b><p>Populatie, methode, uitkomst en beperkingen.</p></div></div>'],
rights:["Rechten",'<div class="rights-flow"><span>KENNIS</span><b class="arrow">→</b><span>RICHTLIJN</span><b class="arrow">→</b><span>BEHANDELAAR</span><b class="arrow">↔</b><span>MV</span></div>'],
explore:["Andere kijk",'<div class="topic-cloud">'+cloud.map(x=>'<button>'+x+'</button>').join("")+'</div><p class="empty">Iedere route krijgt dezelfde vragen: wat is het, waarop is het gebaseerd, wat is onderzocht, wat weten we wel/niet en kan het betrekking hebben op MV?</p>']
};
function open(k){if(k==="questions"){let a=JSON.parse(localStorage.getItem("mv_questions")||"[]");$("#workspaceTitle").textContent="Vragen";$("#workspaceBody").innerHTML=a.length?a.map((q,i)=>'<div class="saved-question"><span>'+esc(q)+'</span><button data-del="'+i+'">verwijder</button></div>').join(""):'<p class="empty">Nog geen vragen bewaard.</p>';$$("[data-del]").forEach(b=>b.onclick=()=>{a.splice(+b.dataset.del,1);localStorage.setItem("mv_questions",JSON.stringify(a));open("questions")});return}let v=views[k];if(!v)return;$("#workspaceTitle").textContent=v[0];$("#workspaceBody").innerHTML=v[1]}
$$("[data-view]").forEach(b=>b.addEventListener("click",()=>open(b.dataset.view)));open("explore");